# Generated by Django 4.1.1 on 2022-09-25 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido_animal', models.CharField(max_length=100)),
                ('img_animal', models.ImageField(upload_to='')),
                ('sit_animal', models.CharField(choices=[('R', 'RUA'), ('T', 'TRATAMENTO'), ('A', 'ADOTADO'), ('L', 'LAR TEMPORÁRIO')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PortoSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('titulo', models.TextField(default='<django.db.models.query_utils.DeferredAttribute object at 0x7ff1fbb2a700> |     <django.db.models.fields.FloatField> | <django.db.models.fields.FloatField>')),
                ('casa', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1, verbose_name='Disponível: Casa, Água, Comida')),
                ('protetor', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('qtd_animais', models.IntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField(auto_now=True)),
                ('data_final', models.DateField()),
                ('titulo', models.CharField(max_length=100)),
                ('finalidade', models.CharField(max_length=250)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
