# Generated by Django 4.1.1 on 2022-09-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='data_final',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='data_inicial',
            field=models.DateTimeField(default='25/09/2022'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='finalidade',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='portoseguro',
            name='titulo',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
