# Generated by Django 4.1.1 on 2022-10-04 22:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_animais', '0002_remove_animal_username_alter_animal_img_animal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanha',
            name='username',
        ),
        migrations.AddField(
            model_name='animal',
            name='username',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='data_inicial',
            field=models.DateField(default=datetime.date(2022, 10, 4)),
        ),
    ]
