# Generated by Django 4.1.1 on 2022-09-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_animais', '0002_alter_campanha_data_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='data_final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='data_inicial',
            field=models.DateField(default='25/09/2022'),
        ),
    ]
