# Generated by Django 4.1.1 on 2022-10-05 22:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_animais', '0003_remove_campanha_username_animal_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='apelido_animal',
            field=models.CharField(max_length=100, verbose_name='Apelido do Animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='img_animal',
            field=models.ImageField(upload_to='fotos_animais', verbose_name='Foto do Animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sit_animal',
            field=models.CharField(choices=[('R', 'RUA'), ('T', 'TRATAMENTO'), ('A', 'ADOTADO'), ('L', 'LAR TEMPORÁRIO')], max_length=50, verbose_name='Situação do Animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='data_inicial',
            field=models.DateField(default=datetime.date(2022, 10, 5)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'O usuário cadastrado já existe!'}, max_length=50, unique=True, verbose_name='Usuário'),
        ),
    ]
