# Generated by Django 4.1.1 on 2022-09-25 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_animais', '0004_alter_campanha_data_inicial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campanha',
            old_name='autor',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='portoseguro',
            old_name='autor',
            new_name='username',
        ),
        migrations.AddField(
            model_name='animal',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
