# Generated by Django 4.1.1 on 2022-10-07 22:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_animais', '0004_alter_animal_apelido_animal_alter_animal_img_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='username',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='data_inicial',
            field=models.DateField(default=datetime.date(2022, 10, 7)),
        ),
        migrations.AlterField(
            model_name='portoseguro',
            name='username',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
