# Generated by Django 4.1.1 on 2022-10-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_animais', '0005_campanha_username_alter_campanha_data_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='data_final',
            field=models.DateField(blank=True, null=True),
        ),
    ]
