# Generated by Django 4.1.1 on 2022-10-08 14:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_animais', '0006_alter_campanha_data_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='animal',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='api_animais.animal'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='data_inicial',
            field=models.DateField(default=datetime.date(2022, 10, 8)),
        ),
        migrations.AlterField(
            model_name='portoseguro',
            name='titulo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
