# Generated by Django 4.1.1 on 2022-10-08 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_animais', '0007_campanha_animal_alter_campanha_data_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='animal',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='api_animais.animal'),
        ),
    ]
