# Generated by Django 4.1.1 on 2022-10-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_animais', '0008_alter_campanha_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='animal',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api_animais.animal'),
        ),
    ]
