# Generated by Django 4.1.1 on 2022-10-21 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_animais', '0010_rename_finalidade_campanha_informacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='data_inicial',
            field=models.DateField(default=datetime.date(2022, 10, 20)),
        ),
    ]
