# Generated by Django 5.2.8 on 2025-11-09 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_animais", "0016_alter_campanha_data_inicial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campanha",
            name="data_inicial",
            field=models.DateField(default=datetime.date(2025, 11, 9)),
        ),
    ]
