# Generated by Django 5.2.8 on 2025-11-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_animais", "0017_alter_campanha_data_inicial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
